from agent.models.types import PulseReport
from agent.rendering.models import EmailContent
from agent.rendering.report_renderer import _sentiment_emoji

def render_email(report: PulseReport, doc_link: str) -> EmailContent:
    product_name = report.product.capitalize()
    iso_week = report.iso_week.upper()
    
    subject = f"{product_name} Review Pulse — Week {iso_week}"
    
    # Render HTML Body
    html_body = f"""<p>Hi team,</p>

<p>This week's review pulse for <strong>{product_name}</strong> is ready.
We analyzed <strong>{report.total_reviews_analyzed} reviews</strong>.</p>

<h3>Top Themes</h3>
<ul>
"""
    for theme in report.themes:
        emoji = _sentiment_emoji(theme.sentiment)
        html_body += f"  <li>{emoji} {theme.name} — {theme.description}</li>\n"
        
    html_body += f"""</ul>

<p>
  <a href="{doc_link}">
    📄 Read full report in Google Docs
  </a>
</p>

<p style="color: #888; font-size: 12px;">
  Auto-generated by Weekly Review Pulse &middot; {report.generated_at.strftime("%a %b %d, %Y").replace(" 0", " ")}
</p>"""

    # Render Text Body
    text_body = f"""Hi team,

This week's review pulse for {product_name} is ready.
We analyzed {report.total_reviews_analyzed} reviews.

Top Themes:
"""
    for theme in report.themes:
        emoji = _sentiment_emoji(theme.sentiment)
        text_body += f" - {emoji} {theme.name} — {theme.description}\n"
        
    text_body += f"""
📄 Read full report in Google Docs:
{doc_link}

Auto-generated by Weekly Review Pulse · {report.generated_at.strftime("%a %b %d, %Y").replace(" 0", " ")}
"""
    
    return EmailContent(
        subject=subject,
        html_body=html_body,
        text_body=text_body.strip()
    )
