from typing import List
from thefuzz import fuzz
from agent.models.types import Quote, Review

def validate_quotes(quotes: List[Quote], all_reviews: List[Review]) -> List[Quote]:
    """Ensures that the quotes generated by the LLM actually exist in the source data using fuzzy matching and ellipsis support."""
    valid_quotes = []
    
    for quote in quotes:
        quote.validated = False
        
        # Clean up ellipses and quotes
        cleaned_q = quote.text.strip(' ."\'…')
        if cleaned_q.startswith('...'):
            cleaned_q = cleaned_q[3:].strip()
        if cleaned_q.endswith('...'):
            cleaned_q = cleaned_q[:-3].strip()
            
        normalized_q = cleaned_q.lower()
        
        best_match_score = 0
        best_review = None
        
        for r in all_reviews:
            r_text_lower = r.text.lower()
            
            # 1. Try exact substring first (fastest)
            if normalized_q in r_text_lower:
                best_match_score = 100
                best_review = r
                break
                
            # 2. Try fuzzy partial match (typo tolerant)
            # partial_ratio finds the best matching substring
            score = fuzz.partial_ratio(normalized_q, r_text_lower)
            if score > best_match_score:
                best_match_score = score
                best_review = r
                
        # Threshold for validation
        if best_match_score >= 85 and best_review:
            quote.validated = True
            quote.rating = best_review.rating
            
        valid_quotes.append(quote)
        
    return valid_quotes
